### ISSUE TITLE
The function signature doesn't match the parent. Parent signature is "_calculate_forces(float = <default>) -> PackedVector3Array".

### ISSUE THREAD

**Issue by LeoBlanchette** [addmix/godot_aerodynamic_physics#22]
I'm probably seeing something wrong here, but I am getting this error. 
[edit, it only shows when I use visual code...its probably not a real problem.]

**Comment by addmix** [comment]
That means when you wrote `func _calculate_forces():` you probably forgot to include the parameter `substep_delta` that is required for the function.

I'm not sure what configuration will be required on your end for visual code to use the correct parameters and return type.
