### ISSUE TITLE
does it works on terrestrial vehicles?

### ISSUE THREAD

**Issue by lucasthomaz97** [addmix/godot_aerodynamic_physics#25]
i see that every showcase you have are for airplanes and helicopters, flying vehicles, i just want to know if i it would work in an arcade car  game or an f-zero like game, to have aerodynamics for terrestrial vehicles would be really cool!
i'm only writing this on the issues page because i didn't found any other place to discuss about the addon in itself, to make questions like that.
anyway, nice work!

**Comment by addmix** [comment]
Yeah, absolutely! The AeroBody node is an extension of VehicleBody, so Godot's VehicleWheel nodes still work, but so long as you have some form of physics-based movement, you can have the aerodynamics contribute.
