### ISSUE TITLE
Drone

### ISSUE THREAD

**Issue by Amzu-bzh** [addmix/godot_aerodynamic_physics#26]
# Create a drone

Hi, I want to create an FPV drone simulator in Godot, but I've explored your plugin and I haven't found any system to create a drone.

Is it possible to create a drone with your plugin ?
If yes, which node have I to use ?

**Comment by addmix** [comment]
By "drone", I assume you mean a quadcopter type drone? You can use the AeroPropeller3D node, using ManualAeroSurface nodes as the propeller blades. You can configure the control system to change the propeller speed based on control inputs, as a real quadcopter would.

I have a quadcopter test scene that I can send you in a few hours.

**Comment by Amzu-bzh** [comment]
Ok, thank you very much and yes, I mean a quadcopter.
I wouldn't be against your quadcopter test scene.

**Comment by addmix** [comment]
Here's the scene and the script, transferring files to GitHub is a little bit difficult on mobile, lol.

There might be a dependency on a camera script I have in my project, you can ignore it and the scene will still work.

[quadcopter.tscn](https://github.com/user-attachments/files/17689089/quadcopter.tscn.2.txt)
[quadcopter.gd](https://github.com/user-attachments/files/17689090/quadcopter.gd.txt)
