### ISSUE TITLE
Throttle Not Decreasing

### ISSUE THREAD

**Issue by Extra-Nuclear** [addmix/godot_aerodynamic_physics#27]
For some reason, when I press the throttle down key bind, nothing happens and the plane doesn't slow. Is there any way of visualising the throttle to see if it is decreasing.

**Comment by Extra-Nuclear** [comment]
Also, the brakes don't seem to be working

**Comment by addmix** [comment]
Can you share your project files, or at minimum your AeroBody scene?

**Comment by addmix** [comment]
Looks like this issue is already solved in the main branch, so I've pushed out a new release, 0.6.0. Let me know if you have any other issues after updating.

**Comment by Extra-Nuclear** [comment]
I think the throttle is decresing, however, i'm not sure the brakes are working. I have the "Brake Control -> Positive Event" set to the space bar, however, the plane seems to not be slowing down. I have some labels on the side of the screen, using the AeroUnits Global, showing Altitude and Speed. When the plane is on the ground, and I hold the space bar, the plane slows, but very very slowly, but I think this is not the brakes doing the slowing. Is there a way of visually showing the power of the throttle?

**Comment by addmix** [comment]
There's not really a way to display throttle, other than printing the AeroBody throttle.

As for the brakes, are you trying to use the vehicle wheel brakes? My control system doesn't interact with the VehicleWheels, but maybe I should adjust it so that it does.

**Comment by Extra-Nuclear** [comment]
Printing the AeroBody throttle should work, how can I do this?

For the brakes, I have attached a seperate script to some VehicleWheels, and that seems to work.

**Comment by Extra-Nuclear** [comment]
Its fine I worked it out. Thanks.
