### ISSUE TITLE
AeroVariablePropeller3D not rotating in some cases, along with no force being generated.

### ISSUE THREAD

**Issue by cyteon** [addmix/godot_aerodynamic_physics#28]
This issue is occurring really randomly, and is hard to reproduce.
In some cases, when i, or other people, test my game, in some cases the propeller just wont spin.
We can confirm at thrust is to 100% as the propeller sounds get louder, and the thrust stick gets pushed in.

Relevant scenes/nodes (ask if you need anything else)
![image](https://github.com/user-attachments/assets/5767d829-d15b-4cb4-a686-f1e53732b70e)
![image](https://github.com/user-attachments/assets/fa1aff3c-c80d-4566-b1f0-7f7609f1f8fe)
![image](https://github.com/user-attachments/assets/87adaddb-803f-4bdb-9d89-3d0848fddb10)

My game is open source @ https://github.com/cyteon/PlenFS if you wanna look at code

**Comment by cyteon** [comment]
Binaries for game can be found at https://cyteon.itch.io/plenfs?secret=aUyXBK35Mi5j4Fm59uarFMOBNKs

**Comment by addmix** [comment]
From my testing of your project, it seems that the airplane is falling asleep. The quick workaround is to set `can_sleep` to false on the AeroBody. However, this does bring up an important point that currently, aerodynamic forces aren't being calculated to wake the body from sleep. The aerodynamic calculations are disabled when the body falls asleep, for performance reasons, however I guess it would make sense that a change in air velocity, or a change in influencer transform should cause the body to wake.

Though, your project looks very promising. I am interested in seeing what you are able to do with it.

**Comment by cyteon** [comment]
I'll try to change the can_sleep to false, and see if that works. Also thanks for showing a interest in my project :D

**Comment by cyteon** [comment]
Appears fixed

**Comment by addmix** [comment]
21dd2deac87fe9a6fdba4af448cc5486157c468f Should be a better solution than disabling `can_sleep` on AeroBody nodes. It should all be automatic, no config needed on your end.
